import { PosterTheme } from './types';

export const THEMES: PosterTheme[] = [
  {
    id: 'christmas',
    title: '圣诞海报',
    color: '#2E7D32',
    mainPoster: {
      id: 'christmas-main',
      title: '圣诞主海报',
      imageUrl: '/posters/christmas/main.webp',
      width: 800,
      height: 1200,
    },
    extensions: [
      {
        id: 'christmas-playlist',
        title: '歌单',
        imageUrl: '/posters/christmas/playlist.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'christmas-event',
        title: '活动详情',
        imageUrl: '/posters/christmas/event-detail.webp',
        width: 800,
        height: 1200,
      },
    ],
    description: '圣诞主题系列活动海报设计',
  },
  {
    id: 'advent-calendar',
    title: '圣诞活动日历',
    color: '#E57373',
    mainPoster: {
      id: 'advent-main',
      title: '活动日历海报',
      imageUrl: '/posters/advent-calendar/main.webp',
      width: 800,
      height: 1200,
    },
    extensions: [
      {
        id: 'advent-style-1',
        title: '风格一',
        imageUrl: '/posters/advent-calendar/style-1.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'advent-style-2',
        title: '风格二',
        imageUrl: '/posters/advent-calendar/style-2.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'advent-style-3',
        title: '风格三',
        imageUrl: '/posters/advent-calendar/style-3.webp',
        width: 800,
        height: 1200,
      },
    ],
    description: '圣诞倒计时日历多种风格设计',
  },
  {
    id: 'womens-day',
    title: '妇女节海报',
    color: '#D47B9E',
    mainPoster: {
      id: 'womensday-main',
      title: '妇女节主海报',
      imageUrl: '/posters/womens-day/main.webp',
      width: 800,
      height: 1200,
    },
    extensions: [
      {
        id: 'womensday-playlist',
        title: '歌单详情',
        imageUrl: '/posters/womens-day/playlist-detail.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'womensday-event',
        title: '活动详情',
        imageUrl: '/posters/womens-day/event-detail.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'womensday-prize',
        title: '活动奖品',
        imageUrl: '/posters/womens-day/prize-detail.webp',
        width: 800,
        height: 1200,
      },
    ],
    description: '三八妇女节主题海报及延展物料',
  },
  {
    id: 'photography',
    title: '摄影海报',
    color: '#FFD54F',
    mainPoster: {
      id: 'photo-main',
      title: '摄影海报一',
      imageUrl: '/posters/photography/poster-1.webp',
      width: 800,
      height: 1200,
    },
    extensions: [
      {
        id: 'photo-2',
        title: '摄影海报二',
        imageUrl: '/posters/photography/poster-2.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'photo-3',
        title: '摄影海报三',
        imageUrl: '/posters/photography/poster-3.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'photo-4',
        title: '摄影海报四',
        imageUrl: '/posters/photography/poster-4.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'photo-5',
        title: '摄影海报五',
        imageUrl: '/posters/photography/poster-5.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'photo-6',
        title: '摄影海报六',
        imageUrl: '/posters/photography/poster-6.webp',
        width: 800,
        height: 1200,
      },
    ],
    description: '摄影作品系列海报设计',
  },
  {
    id: 'lantern-festival',
    title: '元宵海报',
    color: '#FFB74D',
    mainPoster: {
      id: 'lantern-main',
      title: '元宵主海报',
      imageUrl: '/posters/lantern-festival/main.webp',
      width: 800,
      height: 1200,
    },
    extensions: [],
    description: '元宵节主题海报设计',
  },
  {
    id: 'jd-ecommerce',
    title: '京东电商主图',
    color: '#2196F3',
    mainPoster: {
      id: 'jd-main',
      title: '硅胶弦乐器',
      imageUrl: '/posters/jd-ecommerce/main.webp',
      width: 800,
      height: 1200,
    },
    extensions: [
      {
        id: 'jd-ext-2',
        title: '0基础入门',
        imageUrl: '/posters/jd-ecommerce/ext-2.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'jd-ext-6',
        title: '露营好物',
        imageUrl: '/posters/jd-ecommerce/ext-6.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'jd-ext-3',
        title: '三阶段成长',
        imageUrl: '/posters/jd-ecommerce/ext-3.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'jd-ext-4',
        title: '自营好物',
        imageUrl: '/posters/jd-ecommerce/ext-4.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'jd-ext-5',
        title: '自营优选',
        imageUrl: '/posters/jd-ecommerce/ext-5.webp',
        width: 800,
        height: 1200,
      },
      {
        id: 'jd-ext-1',
        title: '自学有乐趣',
        imageUrl: '/posters/jd-ecommerce/ext-1.webp',
        width: 800,
        height: 1200,
      },
    ],
    description: '京东电商日常主图设计，涵盖乐器、户外、自营等多品类视觉',
  },
];
